name: Django CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: vardaan
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: 127.0.0.1
      DB_NAME: vardaan
      DB_USER: root
      DB_PASSWORD: root

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be Ready
      run: |
        for i in {1..30}; do
          mysqladmin ping -h 127.0.0.1 -uroot -proot && break
          echo "Waiting for MySQL..."
          sleep 2
        done

    - name: Run Migrations
      run: python manage.py migrate

    - name: Run Unit Tests
      run: python manage.py test

    - name: Run Bandit Security Scan
      run: |
        pip install bandit
        bandit -r . -lll -ii

    - name: Run Semgrep Static Code Scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: "p/ci"

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Run Snyk Scan
      run: snyk test --file=requirements.txt --sarif-file-output=snyk.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Upload Snyk SARIF to GitHub
      uses: github/codeql-action/upload-sarif@v3
      with:
         sarif_file: snyk.sarif

    - name: Run Cypress E2E Tests
      run: docker-compose run --rm cypress
      
